global:
  prefect:
    image:
      repository: prefecthq/prefect
      prefectTag: 3-latest
      pullPolicy: IfNotPresent
      pullSecrets: []
    env: []

backgroundServices:
  runAsSeparateDeployment: true
  messaging:
    broker: prefect_redis.messaging
    cache: prefect_redis.messaging
    redis:
      host: ""
      port: 6379
      db: 0
      ssl: false
      username: ""
      password: ""

redis:
  enabled: true