server:
  image:
    repository: prefecthq/prefect
    prefectTag: 3.1.13.dev4-python3.9
  services:
    enabled: true
    replicaCount: 1
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
  # Main server resources
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi 