{{- if and .Values.postgresql.enabled (not .Values.postgresql.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "orion.postgres-string-secret-name" . | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "orion.labels" . | nindent 4 }}
type: Opaque
data:
  connection-string: {{ include "orion.postgres-connstr" . | b64enc | quote  }}
{{- end }}
