{{- if .Values.server.loopServices.enabled }}
apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "common.names.fullname" . }}-loop-services
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: loop-services
    prefect-version: {{ .Chart.AppVersion }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.server.loopServices.replicaCount }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: loop-services
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: loop-services
        prefect-version: {{ .Chart.AppVersion }}
    spec:
      serviceAccountName: {{ template "server.serviceAccountName" . }}
      {{- if .Values.server.podSecurityContext }}
      securityContext: {{- .Values.server.podSecurityContext | toYaml | nindent 8 }}
      {{- end }}
      containers:
        - name: prefect-services
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.prefectTag }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          command:
            - /usr/bin/tini
            - -g
            - --
            - /opt/prefect/entrypoint.sh
          args:
            - prefect
            - server
            - services
            - start
          env:
            - name: HOME
              value: /home/prefect
            - name: PREFECT_API_URL
              value: {{ .Values.server.prefectApiUrl | quote }}
            - name: PREFECT_DEBUG_MODE
              value: {{ .Values.server.debug | quote }}
            - name: PREFECT_LOGGING_SERVER_LEVEL
              value: {{ .Values.server.loggingLevel | quote }}
            - name: PREFECT_API_DATABASE_CONNECTION_URL
              {{- if .Values.sqlite.enabled }}
              value: "sqlite+aiosqlite:////data/prefect.db"
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "server.postgres-string-secret-name" . }}
                  key: connection-string
              {{- end }}
            {{- if .Values.server.env }}
            {{- include "common.tplvalues.render" (dict "value" .Values.server.env "context" $) | nindent 12 }}
            {{- end }}
          envFrom:
            {{- if .Values.server.extraEnvVarsCM }}
            - configMapRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.server.extraEnvVarsCM "context" $) }}
            {{- end }}
            {{- if .Values.server.extraEnvVarsSecret }}
            - secretRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.server.extraEnvVarsSecret "context" $) }}
            {{- end }}
          {{- if .Values.server.loopServices.resources }}
          resources: {{- toYaml .Values.server.loopServices.resources | nindent 12 }}
          {{- end }}
          {{- with .Values.server.containerSecurityContext }}
          securityContext: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.sqlite.enabled }}
          volumeMounts:
            - mountPath: /data
              name: sqlite-storage
          {{- end }}
          volumeMounts:
            - mountPath: /home/prefect
              name: scratch
              subPathExpr: home
            - mountPath: /tmp
              name: scratch
              subPathExpr: tmp
      {{- if .Values.sqlite.enabled }}
      volumes:
        - name: sqlite-storage
          persistentVolumeClaim:
            claimName: {{ template "common.names.fullname" . }}-sqlite
      {{- end }}
      volumes:
        - name: scratch
          emptyDir: {}
{{- end }} 