---
sources:
  common:
    kind: helmchart
    spec:
      url: https://charts.bitnami.com/bitnami
      name: common
      versionFilter:
        kind: semver
    sourceid: common
  postgresql:
    kind: helmchart
    spec:
      url: https://charts.bitnami.com/bitnami
      name: postgresql
      versionFilter:
        kind: semver
    sourceid: postgresql
conditions: {}
targets:
  prometheus_prefect_exporter_common:
    name: bump chart dependencies
    kind: yaml
    spec:
      file: charts/prometheus-prefect-exporter/Chart.yaml
      key: dependencies[0].version
    sourceid: common
  server_common:
    name: bump chart dependencies
    kind: yaml
    spec:
      file: charts/prefect-server/Chart.yaml
      key: dependencies[0].version
    sourceid: common
  worker_common:
    name: bump chart dependencies
    kind: yaml
    spec:
      file: charts/prefect-worker/Chart.yaml
      key: dependencies[0].version
    sourceid: common
  server_postgresql:
    name: bump chart dependencies
    kind: yaml
    spec:
      file: charts/prefect-server/Chart.yaml
      key: dependencies[1].version
    sourceid: postgresql
