
---
# Source: prefect-orion/templates/api/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orion-prefect-orion-api
  labels:
    helm.sh/chart: prefect-orion-1.0.0
    app.kubernetes.io/name: prefect-orion
    app.kubernetes.io/instance: orion
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: prefect-orion
      app.kubernetes.io/instance: orion
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prefect-orion
        app.kubernetes.io/instance: orion
    spec:
      serviceAccountName: orion-prefect-orion
      securityContext:
        {}
      containers:
        - name: prefect-orion
          securityContext:
            {}
          image: "prefecthq/prefect:2-latest"
          imagePullPolicy: IfNotPresent
          command: ["prefect", "orion", "start", "--host", "0.0.0.0", "--log-level", "WARNING", "--port", "4200"]
          ports:
          - containerPort: 4200
          resources:
            {}
          env:
            - name: PREFECT_DEBUG_MODE
              value: "false"
            - name: PREFECT_ORION_DATABASE_CONNECTION_URL
              valueFrom:
                secretKeyRef:
                  name: orion-postgresql-connection
                  key: connection-string
