api:
  enabled: true
  service:
    type: ClusterIP
    port: 4200

  replicaCount: 1

  image:
    name: prefecthq/prefect
    pullPolicy: IfNotPresent
    # -- Overrides the image tag whose default is the chart appVersion.
    tag: 2-latest

    pullSecrets: []
    ## Optionally specify an array of imagePullSecrets.
    ## Secrets must be manually created in the namespace.
    ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
    ##
    # pullSecrets:
    #   - myRegistrKeySecretName

  debugEnabled: false

  # -- Custom enviornment variables
  env: {}
  # Allow custom variables to be added to the deployment
  # - name: PREFECT_API_URL
  #   value: http://prefect-server:4200/api

  autoscaling:
    # -- Enable autoscaling
    enabled: false
    # -- Minimum autoscaling replica count
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  # -- Ingress configuration
  ingress:
    enabled: false
    className: ""
    annotations: {}
    hosts:
      - host: prefect.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []

  nodeSelector: {}
  tolerations: []
  affinity: {}
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  resources: {}

postgresql:
  enabled: true
  auth:
    database: orion

    # postgresqlUsername defines the username to authenticate
    # with.
    # NOTE: If you are using Azure, this will include an '@'
    # which must be encoded as '%40' for the connection string
    # to work with both Hasura, the GraphQL server, and the
    # Alembic migration manager
    username: prefect

    # password sets the password to be used if
    # `existingSecret` is not set. This is the password for
    # `username` and will be set within the secret at
    # the key `postgresql-password`. This argument is only relevant
    # when using the Postgres database included in the chart.
    # For an external postgres connection, you must create
    # and use `existingSecret` instead of `postgresqlPassword`.
    # password: "HEREWEGO"

    # existingSecret configures which secret should be referenced
    # for access to the database. If null and `useSubChart` is
    # enabled, the secret will be generated. If using an external
    # postgres service, this value should be set to the name of
    # an existing Kubernetes secret. This secret must contain
    # a key-value pair where the key is `connection-string`
    # and the value is the connection string containing your
    # password (e.g. postgresql+asyncpg://{username}:{password}@{hostname}/{database}).
    existingSecret: null

  # servicePort configures the port that the database should be
  # accessed at
  containerPorts:
    postgresql: 5432

  # externalHostname defines the address to contact an externally
  # managed postgres database instance at. This is not required if
  # `internalPostgres` is `true`
  externalHostname: ""

  # useSubChart determines if a this chart should deploy a
  # user-manager postgres database or use an externally managed
  # postgres instance. If `useSubChart` is `true`, the
  # bitnami/postgresql subchart will be deployed
  useSubChart: true

  # postgresql configuration below here is only used if using
  # the subchart

  # persistence enables a PVC that stores the database between
  # deployments. If making changes to the database deployment, this
  # PVC will need to be deleted for database changes to take effect.
  # This is especially notable when the authentication password
  # changes on redeploys.
  # This is disabled by default because we do not recommend using
  # the subchart deployment for production deployments.
  persistence:
    # -- Enables a PVC that stores db between deployments
    enabled: false
    # -- Configures size of postgres PVC
    size: 8Gi

  # initial postgres user to create
  primary:
    initdb:
      user: postgres

  image:
    # -- Version tag, corresponds to tags at https://hub.docker.com/r/bitnami/postgresql/
    tag: 14.3.0

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  # If set and create is false, resources will point to this external service account
  name: ""
