{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "prometheus-prefect-exporter.fullname" . }}
  labels:
    {{- include "prometheus-prefect-exporter.labels" . | nindent 4 }}
spec:
  jobLabel: "{{ .Release.Name }}"
  selector:
    matchLabels:
      {{- include "prometheus-prefect-exporter.selectorLabels" . | nindent 8 }}
  endpoints:
  - port: http
    interval: {{ .Values.serviceMonitor.interval | quote }}
    scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout | quote }}
    {{- if .Values.serviceMonitor.metricRelabelings }}
    metricRelabelings:
    {{- toYaml .Values.serviceMonitor.metricRelabelings | nindent 4 }}
    {{- end }}
    {{- if .Values.serviceMonitor.relabelings }}
    relabelings:
    {{- toYaml .Values.serviceMonitor.relabelings | nindent 4 }}
    {{- end }}
{{- end -}}
