# See https://github.com/helm/chart-testing#configuration
charts:
  - charts/prefect-server
chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami
helm-extra-args: --timeout 90s
release-label: prefect
