# See https://github.com/helm/chart-testing#configuration
charts:
  - charts/prefect-worker
chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami
helm-extra-args: --timeout 600s
namespace: prefect
release-label: prefect
