---
name: Mark stale issues/PRs

on:
  schedule:
    #        ┌───────────── minute (0 - 59)
    #        │  ┌───────────── hour (0 - 23)
    #        │  │  ┌───────────── day of the month (1 - 31)
    #        │  │  │ ┌───────────── month (1 - 12 or JAN-DEC)
    #        │  │  │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #        │  │  │ │ │
    #        │  │  │ │ │
    #        │  │  │ │ │
    - cron: "00 7 * * *"  # 7a UTC, 12a PST

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v8
        with:
          # https://github.com/actions/stale#all-options
          repo-token: ${{ github.token }}
          # Issues
          stale-issue-label: "stale"
          days-before-issue-stale: 60
          stale-issue-message: "This issue is stale because it has been open for 60 days with no activity. Are there any updates?"
          days-before-issue-close: 30
          close-issue-message: "This issue was closed because it has been inactive for 30 days since being marked as stale."
          # PRs
          stale-pr-label: "stale"
          days-before-pr-stale: 30
          stale-pr-message: "This PR is stale because it has been open for 30 days with no activity. Are there any updates?"
          days-before-pr-close: 14
          close-pr-message: "This PR was closed because it has been inactive for 14 days since being marked as stale."
