---
name: Lint and Test Prefect Worker Chart

"on":
  pull_request:
    branches:
      - main

permissions:
  # required to read from the repo
  contents: read

jobs:
  lint_test:
    name: "lint-test (${{ matrix.kubernetes }})"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kubernetes:
          - "1.31.0"
          - "1.32.0"
          - "1.33.0"
          - "1.34.0"
      fail-fast: false

    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Set up Helm
        uses: azure/setup-helm@v5

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.8.0

      - name: Run chart-testing (lint)
        run: ct lint --config .github/linters/worker-ct.yaml

      - name: Create kind cluster
        uses: helm/kind-action@v1.14.0
        with:
          node_image: "kindest/node:v${{ matrix.kubernetes }}"

      - name: Create worker namespace
        run: kubectl create namespace prefect

      - name: Install Prefect Server
        run: |
          helm dependency build ./charts/prefect-server/
          helm install prefect-server -n default ./charts/prefect-server/ \
            --set=postgresql.auth.password=TESTING \
            --wait \
            --timeout 5m

      - name: Run chart-testing (install)
        run: |
          ct install --config .github/linters/worker-ct.yaml --helm-extra-set-args "--set=worker.config.workPool=repo-prefect-helm-gha-workflow-tests --set=worker.apiConfig=selfHostedServer --set=worker.selfHostedServerApiConfig.apiUrl=http://prefect-server.default.svc.cluster.local:4200/api"
